### ISSUE TITLE
Lab

### ISSUE THREAD

**Issue by pacosta613** [learn-co-curriculum/activerecord-tvshow#11]
ActiveRecord::StatementInvalid:
       Could not find table 'shows'

even though i did create the table. I submitted my code github. 

Also, in the active record section, the translating from ORM to ActiveRecord doesn't display the green pass tests. Maybe a bug there too. 

Thanks!

**Comment by AnnJohn** [comment]
thanks @pacosta613, we'll look into the first part of your issue. 

For the second part with the green lights, this is a bug so could you file a bug report? If you hover over your name in Learn, you'll see an option to report a bug. Thanks!

**Comment by vicfriedman** [comment]
hey @pacosta613 

Thanks so much for opening an issue. I just walked through this lab, and got the same error as you, when I had created and ran the migrations, but hadn't created the `Show` model yet. I cloned your solution and your tests all seem to pass. I'm going to go ahead and close this issue. Please feel free to re-open or comment back if you think this is still a problem
