### ISSUE TITLE
Permission of ./db folder

### ISSUE THREAD

**Issue by MondoGao** [learn-co-curriculum/activerecord-tvshow#18]
I was working with Learn IDE in Windows, and Readme.md told me I needed to make a new folder "db"
I did it, but when I run `rake db:migrate`, I got `SQLite3::CantOpenException: unable to open database file`
I solve this by commit and re-clone(I can't chmod directly), and this may cause confusion to others.

**Comment by bhollan** [comment]
This is still an issue.  The above solution worked for a student I helped.

I was able to duplicate on Linux, so I don't think it's OS-based (but I don't know).

To re-create: Clone/cd the lab, right-click `labs` -> New Folder
Then run `ls -alh` in the terminal to see the permissioned user is `root`, which will not run on the IDE.

Workaround: Creating the folder(s) with `mkdir db` and then `mkdir db/migrate` creates the folders with the proper permissions.

CC: @aturkewi
