### ISSUE TITLE
uninitialized constant ConnectionAdapter

### ISSUE THREAD

**Issue by anytimesoon** [learn-co-curriculum/activerecord-tvshow#20]
The connection adapter class is no required anywhere in the project.

I added the following code to the /lib/support/db_registry.rb

`require_relative 'connection_adapter'`

This made it work

**Comment by itzsaga** [comment]
I just ran into this as well. Thanks @anytimesoon

**Comment by bhollan** [comment]
Ran into this one again today.

CC: @aturkewi

**Comment by jblair87** [comment]
Hi, 
You need to add require_relative "./connection_adapter.rb"   to the lib/support/db_registry.rb file. 
There is another issue with this lab though.

**Comment by HimaChitalia** [comment]
@anytimesoon .. This solution helped me too! Thanks a lot. 👍
