### ISSUE TITLE
rake db:migrate no method defined []

### ISSUE THREAD

**Issue by hysan** [learn-co-curriculum/activerecord-tvshow#27]
Student gets the following error when running `rake db:migrate`:

```
-- [](4.2)
-- [](4.2)
rake aborted!
NoMethodError: undefined method `[]' for #<ActiveRecord::Migration:0x007ff0c81f75a0>
/Users/yapjinai/.rvm/gems/ruby-2.3.3/gems/activerecord-4.2.5/lib/active_record/migration.rb:664:in `block in method_missing'
/Users/yapjinai/.rvm/gems/ruby-2.3.3/gems/activerecord-4.2.5/lib/active_record/migration.rb:634:in `block in say_with_time'
/Users/yapjinai/.rvm/gems/ruby-2.3.3/gems/activerecord-
...
```

In their migration, they originally had:

```
class AddSeasonToShows < ActiveRecord::Migration[4.2]
```

But Googling the error points to this [StackOverflow answer](https://stackoverflow.com/questions/48501595/nomethoderror-undefined-method-for-activerecordmigration0x000000033fe) about versioning. Seems like we need to update to 5.x for this lab. The current workaround as suggested by that answer is to remove the versioning from the migration files:

```
class AddSeasonToShows < ActiveRecord::Migration
```

**Comment by sgharms** [comment]
This is a tough call. If the student has a version > 4.2 then doing what you suggest is the right call. If, however, they're versioned to 4.2, they'll need the `[]`. Ultimately, I think this brings up the question on how to make sure that student machines are in a predictable state. As such, I'm going to add this as a +1 to a tracking board where we'll plan the consistent versioning experience. Also as a result, I'm going to close this, but we'll look to slot this work in early 2019.

Steven
