### ISSUE TITLE
Outdated Gem - Inconsistent 

### ISSUE THREAD

**Issue by btmccollum** [learn-co-curriculum/activerecord-tvshow#28]
This lab appears to be using an older version of the ActiveRecord gem which is inconsistent with the other labs leading up to this one in which a version needs to be specified for Migration. Raising issue for consistency's sake with previous labs and to avoid user confusion.

**Comment by drakeltheryuujin** [comment]
Hi @btmccollum,

Thank you for your feedback. The materials have been updated to address this issuse.

Thanks for contributing! 💙
