### ISSUE TITLE
error while installing json when running bundle install

### ISSUE THREAD

**Issue by reduviidae** [learn-co-curriculum/activerecord-tvshow#29]
after running `bundle`:

`An error occurred while installing json (1.8.6), and Bundler cannot
continue.
Make sure that "gem install json -v '1.8.6' --source 'https://rubygems.org/'"
succeeds before bundling.`

after running `gem install json -v '1.8.6'` I get a long error message that begins with `error installing json: ERROR: Failed to build gem native extension`.

when I run `rake -T` or `learn` I get the following error:

`Could not find json-1.8.6 in any of the sources
Run `bundle install` to install missing gems.`

**Comment by drakeltheryuujin** [comment]
Hi @reduviidae, 

I believe it may be Mac OSX Mojave causing issues with the development environment/learn.co platform. I'm unable to reproduce these issues, and [raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) is generally reserved for problems with the Learn.co curriculum. The gems may not be compatible with the latest OS, there's unfortunately not much that we can do to accommodate. You can try the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature, there may be [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) available to help with your specific issues. 

Thanks for contributing, and good luck!
