### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mshin1995** [learn-co-curriculum/activerecord-tvshow#33]
Error caused by putting version next to ActiveRecord::Migration.

**Comment by maxwellbenton** [comment]
Hi @mshin1995,

Thank you for reporting this. I took a look at the master and solution branches and they are working fine without versions listed after ActiveRecord::Migration. Is there a lesson content prior to this that says a migration version should be used? With newer version of ActiveRecord, the need for listing a version should no longer be necessary.

**Comment by maxwellbenton** [comment]
Hi @mshin1995,

We've updated this lesson to ActiveRecord 5.2 and have confirmed that a version is now needed to solve this lab. We've updated the instructions as well, and believe this issue has been resolved.

Thank you for contributing to a Learn lesson!
