### ISSUE TITLE
Confusing rspec

### ISSUE THREAD

**Issue by kjgenevieve** [learn-co-curriculum/activerecord-tvshow#36]
The specs on `highest_rating` and `most_popular_show` ask for the same information, even though `highest_rating` wants an `Integer` and `most_popular_show` wants an Object.

From the spec:
```
  ::highest_rating
    returns the TV show with the highest rating
  ::most_popular_show
    returns the tv show with the highest rating
  ::lowest_rating
    returns the TV show with the lowest rating
  ::least_popular_show
    returns the tv show with the lowest rating
```

Can we change `highest_rating` and `lowest_rating` to say "returns the [highest/lowest] rating of all the tv shows"?

**Comment by sgharms** [comment]
Fixed with commit https://github.com/learn-co-curriculum/activerecord-tvshow/commit/b56646abb23b2b91385dc036de591010d7eeaaa6!
