### ISSUE TITLE
Does not drop db after each test

### ISSUE THREAD

**Issue by sammarcus** [learn-co-curriculum/activerecord-tvshow#6]
This should be `db:drop`ing after each test, or at least after rspec completes? It initially migrates but bad data manifests itself after the first run unless it is dropped.

**Comment by AnnJohn** [comment]
@vicfriedman not sure if this is still an active issue but can you still look at it? thanks.

**Comment by vicfriedman** [comment]
walked all the way through each test in Pry in the solution branch, and the database is being dropped at the end of every test. closing this issue - but @sammarcus please feel free to reopen or comment if you think this is still a problem
